M48
; DRILL file {KiCad 7.0.5} date Thu Aug 10 16:58:00 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-10T16:58:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X189.7Y-96.354
T1
G00X182.65Y-96.354
M15
G01X182.35Y-96.354
M16
G05
T0
M30
